#!/usr/bin/env node
// Generated by CoffeeScript 1.4.0
(function() {
  var charm, client, dgram, msgLine, port, positionForInput, printNewMessage, server, stdin;

  dgram = require("dgram");

  charm = require('charm')();

  server = dgram.createSocket("udp4");

  client = dgram.createSocket("udp4");

  port = 41234;

  server.bind(port);

  server.addMembership('224.0.0.0');

  charm.pipe(process.stdout);

  charm.reset();

  msgLine = 0;

  printNewMessage = function(msg) {
    if (msgLine > process.stdout.getWindowSize()[1] - 3) {
      msgLine = 0;
      charm.erase('screen');
    }
    charm.position(0, ++msgLine);
    charm.write('\u0007');
    return charm.write(msg);
  };

  positionForInput = function() {
    charm.position(0, process.stdout.getWindowSize()[1] - 2);
    charm.background('blue');
    charm.erase('end');
    charm.position(0, process.stdout.getWindowSize()[1] - 1);
    return charm.background('black');
  };

  positionForInput();

  stdin = process.openStdin();

  stdin.on('data', function(msg) {
    msg = new Buffer("[" + process.argv[2] + "] " + (msg.toString()));
    return client.send(msg, 0, msg.length, port, '224.0.0.0', function(err, bytes) {
      positionForInput();
      return charm.erase('end');
    });
  });

  server.on('message', function(msg, rinfo) {
    printNewMessage(msg.toString());
    return positionForInput();
  });

}).call(this);
